model_type: "unet_depthwise"  # Options: "unet", "unet_depthwise", "unet_depthwise_small", "unet_depthwise_nano"
img_size: 256
in_channels: 3
out_channels: 1
checkpoint_path: "checkpoints/exp_20250907_172056/weights/unet_best.pt"
output_model_path: "checkpoints/exp_20250907_172056/ncnn_models/unet_jit.pt"
