img_size: 256
in_channels: 3
out_channels: 1
inference_checkpoint: "checkpoints/exp_20250905_164043/weights/unet_best.pt"
inference_images_dir: "/home/nick/Documents/dataset/bdd100k/images/100k/val"
inference_output_dir: "checkpoints/exp_20250905_164043"