inference_checkpoint: "checkpoints/exp_20250906_223222/weights/unet_best.pt"
inference_images_dir: "/home/nick/Documents/dataset/bdd100k/images/100k/val"
inference_output_dir: "checkpoints/exp_20250906_223222/bdd100k_val_outputs"
model_type: "unet_depthwise_small"  # Options: "unet", "unet_depthwise", "unet_depthwise_small", "unet_depthwise_nano"
img_size: 256
in_channels: 3
out_channels: 1