# UNet Training Configuration
train_images_dir: "/home/nick/Documents/dataset/bdd100k/images/100k/train"
train_masks_dir: "/home/nick/Documents/dataset/bdd100k/labels/lane/masks/train"
val_images_dir: "/home/nick/Documents/dataset/bdd100k/images/100k/val"
val_masks_dir: "/home/nick/Documents/dataset/bdd100k/labels/lane/masks/val"
batch_size: 16
warmup_epochs: 3
epochs: 20
lr: 0.001
img_size: 256
in_channels: 3
out_channels: 1
save_all_epochs: true
save_best_model: true

